name: kelime_kralligi
description: "Kelime Krallığı - Eğlenceli Türkçe Kelime Oyunu"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.4.0
  flutter_tts: ^4.2.5
  google_fonts: ^8.2.0
  just_audio: ^0.10.6
  provider: ^6.1.5+1
  intl: ^0.20.3
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ferhat.png
    - assets/images/hazal.png

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont.ttf